baseURL = "http://reschoolingamerica.org/"
languageCode = "en-us"
title = "Reschooling America"

theme = "jeffprod"

[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"